server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
            - Method=GET,POST
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
okta:
  oauth2:
    issuer: https://dev-51620093.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaf6nhzyorSeu9iT5d7
    client-secret: JKJI8dCVVgUNWUJDJ3OaxcweUfAmSYQ3OepjSqddRcqYNbo3duBuaXo8zZQAVfL5
    scopes: openid, profile, email, offline_access



